kind: pipeline
type: docker
name: develop

steps:
  - name: build-and-push
    image: plugins/gcr
    settings:
      repo: is-eorzea-tominayu/healthy-error-server
      tags: latest
      dockerfile: src/Dockerfile
      context: src/
      json_key:
        from_secret: google_credentials

trigger:
  branch:
    - develop
  event:
    - push
    - pull_request
