kind: pipeline
type: docker
name: develop

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: gcr.is/is-eorzea-tominayu/healthy-error-server
      auto_tag: true
      dockerfile: src/Dockerfile
      context: src/

  - name: publish
    image: plugins/gcr
    settings:
      repo: is-erozea-tominayu/healthy-error-server
      tags: latest
      json_key:
        from_secret: google_credentials

trigger:
  branch:
    - develop
  event:
    - push
    - pull_request
