steps:
  - id: "Inspect workspace"
    name: alpine
    entrypoint: ls
    args:
      - "-l"
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    dir: "src"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/healthy-error-server:$TAG_NAME", "."]
  - id: "Push image to GCR"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/healthy-error-server:$TAG_NAME"]
  - id: "Sed image name"
    name: "alpine"
    dir: "kubernetes"
    entrypoint: "ash"
    args:
      - "-c"
      - |
        sed -i -e 's/IMAGE/gcr.io\/$PROJECT_ID\/healthy-error-server:$TAG_NAME/g' healthy-error-server.yaml
  - id: "Deploy to Kubernetes"
    name: "gcr.io/cloud-builders/kubectl"
    dir: "kubernetes"
    args: ["apply", "-f", "healthy-error-server.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=training-demo"
