apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: healthy-error-server
  annotations:
    traffic.spinnaker.io/load-balancers: '["service healthy-error-server"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: healthy-error-server
      labels:
        app: web
    spec:
      containers:
        - name: healthy-error-server
          image: IMAGE
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: healthy-error-server
spec:
  type: LoadBalancer
  selector:
    frontedBy: healthy-error-server
  ports:
    - port: 80
      targetPort: 80
