apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-error-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: healthy-error-server
      labels:
        app: web
    spec:
      containers:
        - name: healthy-error-server
          image: IMAGE
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: 80
